<?php

return [
    [
        'slug' => 'phototrail',
        'name' => 'PhotoTrail',
        'tag' => 'Shared Event Album',
        'category' => 'React Native - Supabase',
        'desc' => 'A social event-album app where everyone at a wedding or party contributes photos and videos into one shared, private album.',
        'long_desc' => 'PhotoTrail turns every event into a shared memory. Guests join a private album and add photos and videos in real time, so the best shots come from everyone, not just the photographer. With a single living timeline, you relive the day from every angle — long after the event ends.',
        'image' => 'assets/phototrail/pt.webp',
        'image_thumb' => 'assets/phototrail/pt-800.webp',
        'image_width' => 1920,
        'image_height' => 1080,
        'image_thumb_width' => 800,
        'image_thumb_height' => 450,
        'tech' => ['React Native', 'Supabase', 'Expo'],
        'href' => 'https://play.google.com/store/apps/details?id=com.phototrail',
        'live' => 'https://play.google.com/store/apps/details?id=com.phototrail',
        'live_label' => 'View on Play Store',
    ],
    [
        'slug' => 'resq',
        'name' => 'ResQ',
        'tag' => 'Assistance on demand',
        'category' => 'React Native - Node',
        'desc' => 'An on-demand assistance app that connects people with trusted helpers nearby — fast bookings, live tracking, and help whenever you need it.',
        'long_desc' => 'ResQ matches people with trusted local helpers for everyday tasks. Request a service, watch your helper arrive in real time, and pay right in the app. Every part of the flow is built around speed and reliability, so help is never more than a few taps away.',
        'image' => 'assets/portfolios/resq.webp',
        'image_thumb' => 'assets/portfolios/resq-800.webp',
        'image_width' => 1536,
        'image_height' => 1024,
        'image_thumb_width' => 800,
        'image_thumb_height' => 534,
        'tech' => ['React Native', 'Node.js'],
        'href' => 'mailto:ctlinc.faisal@gmail.com?subject=ResQ%20enquiry',
        'live' => null,
    ],
    [
        'slug' => 'fsmobility',
        'name' => 'FsMobility',
        'tag' => 'Taxi Service',
        'category' => 'Laravel Based Dashboard admin Panel',
        'desc' => 'A taxi booking app with live driver tracking, fare estimates, and one-tap ride booking for busy city commuters.',
        'long_desc' => 'FsMobility runs a modern taxi service on a Laravel-powered platform — riders book with one tap, track their driver live, and see fare estimates up front, while a powerful admin dashboard keeps the whole operation in control.',
        'image' => 'assets/phototrail/fsmobility-banner.webp',
        'image_thumb' => 'assets/phototrail/fsmobility-banner-800.webp',
        'image_width' => 1672,
        'image_height' => 941,
        'image_thumb_width' => 800,
        'image_thumb_height' => 451,
        'tech' => ['Laravel', 'Admin Dashboard', 'MySQL'],
        'href' => 'mailto:ctlinc.faisal@gmail.com?subject=FsMobility%20enquiry',
        'live' => 'http://fs-mobility.de',
        'live_label' => 'Visit website',
    ],
    [
        'slug' => 'grubly',
        'name' => 'Grubly',
        'tag' => "Let's all eat up",
        'category' => 'React Native - Laravel',
        'desc' => 'A food ordering app that makes it effortless to browse restaurants, customize meals, and get delivery at the tap of a button.',
        'long_desc' => 'Grubly makes ordering food feel instant. Browse nearby restaurants, customize every meal to your taste, and track your delivery from kitchen to door. A clean, hunger-friendly interface built for the way people actually order food today.',
        'image' => 'assets/portfolios/2.webp',
        'image_thumb' => 'assets/portfolios/2-800.webp',
        'image_width' => 4378,
        'image_height' => 2100,
        'image_thumb_width' => 800,
        'image_thumb_height' => 384,
        'tech' => ['React Native', 'Laravel', 'MySQL'],
        'href' => 'mailto:ctlinc.faisal@gmail.com?subject=Grubly%20enquiry',
        'live' => null,
    ],
    [
        'slug' => 'handiman',
        'name' => 'Handiman.com',
        'tag' => 'Home services',
        'category' => 'Ionic - Laravel',
        'desc' => 'A marketplace connecting homeowners with trusted handymen — simple booking, clear pricing, and service tracking in one place.',
        'long_desc' => 'Handiman.com connects homeowners with vetted handymen for repairs, installations, and maintenance. Book in a few taps, get transparent pricing up front, and follow the job through to completion. A marketplace that makes home services feel reliable again.',
        'image' => 'assets/portfolios/4.webp',
        'image_thumb' => 'assets/portfolios/4-800.webp',
        'image_width' => 5000,
        'image_height' => 3333,
        'image_thumb_width' => 800,
        'image_thumb_height' => 534,
        'tech' => ['Ionic', 'Laravel', 'MySQL'],
        'href' => 'mailto:ctlinc.faisal@gmail.com?subject=Handiman%20enquiry',
        'live' => 'http://handyman.com',
        'live_label' => 'Visit website',
    ],
    [
        'slug' => 'meta-car',
        'name' => 'Meta Car',
        'tag' => 'Car marketplace',
        'category' => 'UI UX Design',
        'desc' => 'A car buying and selling platform with powerful search, rich listings, and instant contact between buyers and sellers.',
        'long_desc' => 'Meta Car is a car marketplace designed around the browsing journey. Powerful search, rich listings with detail-first layouts, and instant contact between buyers and sellers. Every screen was crafted with a focus on UI and UX so the path from search to deal feels effortless.',
        'image' => 'assets/portfolios/5.webp',
        'image_thumb' => 'assets/portfolios/5-800.webp',
        'image_width' => 5000,
        'image_height' => 3333,
        'image_thumb_width' => 800,
        'image_thumb_height' => 534,
        'tech' => ['UI/UX Design', 'Figma', 'Prototyping'],
        'href' => 'mailto:ctlinc.faisal@gmail.com?subject=Meta%20Car%20enquiry',
        'live' => null,
    ],
    [
        'slug' => 'your-results',
        'name' => 'Your Results',
        'tag' => 'Real Time Soccer scores',
        'category' => 'Ionic - Laravel',
        'desc' => 'A results-focused analytics dashboard that turns raw data into clear, actionable insights for smarter business decisions.',
        'long_desc' => 'Your Results brings live soccer action to your pocket with real-time scores, fixtures, and standings updated as they happen. A fast Ionic frontend paired with a Laravel backend keeps fans in the game, wherever they are.',
        'image' => 'assets/portfolios/10.webp',
        'image_thumb' => 'assets/portfolios/10-800.webp',
        'image_width' => 5345,
        'image_height' => 3032,
        'image_thumb_width' => 800,
        'image_thumb_height' => 454,
        'tech' => ['Ionic', 'Laravel', 'MySQL'],
        'href' => 'mailto:ctlinc.faisal@gmail.com?subject=Your%20Results%20enquiry',
        'live' => null,
    ],
    [
        'slug' => 'melvony',
        'name' => 'Melvony',
        'tag' => 'No 1 Social platform',
        'category' => 'React Native - Laravel',
        'desc' => 'A social platform built to connect people and grow communities through a smooth, engaging mobile experience.',
        'long_desc' => 'Melvony is built to be the number one social platform — connecting people, fueling conversations, and growing communities. A React Native app with a Laravel backend delivers a fast, fluid feed that keeps people engaged and coming back.',
        'image' => 'assets/portfolios/01.png',
        'image_width' => 600,
        'image_height' => 600,
        'tech' => ['React Native', 'Laravel', 'MySQL'],
        'href' => 'mailto:ctlinc.faisal@gmail.com?subject=Melvony%20enquiry',
        'live' => 'https://melvony.com',
        'live_label' => 'Visit website',
    ],
    [
        'slug' => 'custom-pennants-football',
        'name' => 'Custom Pennants Football',
        'tag' => 'Custom merchandise',
        'category' => 'Laravel Based E-commerce store',
        'desc' => 'An e-commerce store for custom football pennants with design-your-own tools, team templates, and easy checkout.',
        'long_desc' => 'A complete e-commerce store for custom football pennants. Fans design their own banner, pick from team templates, and check out in seconds. Built on Laravel with a fast, conversion-focused shopping flow and easy store management.',
        'image' => 'assets/phototrail/football_laptop.webp',
        'image_thumb' => 'assets/phototrail/football_laptop-800.webp',
        'image_width' => 753,
        'image_height' => 450,
        'image_thumb_width' => 753,
        'image_thumb_height' => 479,
        'tech' => ['Laravel', 'E-commerce', 'MySQL'],
        'href' => 'mailto:ctlinc.faisal@gmail.com?subject=Custom%20Pennants%20enquiry',
        'live' => 'http://custom-sports-pennants.com/',
        'live_label' => 'Visit website',
    ],
];
